In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"students_data.csv")

In [5]:
df.head(10)

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     31 non-null     int64
 1   name           31 non-null     object
 2   age            28 non-null     float64
 3   gender         31 non-null     object
 4   grade          31 non-null     object
 5   math_score     13 non-null     float64
 6   english_score  23 non-null     object
 7   science_score  31 non-null     int64
 8   enrolled_date  31 non-null     object
 9   remarks        31 non-null     object
dtypes: float64(2), int64(2), object(6)
memory usage: 2.5+ KB

In [7]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
dtype: bool

In [8]:
df = df.drop_duplicates()

In [9]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [11]:
df.shape

(30, 10)

In [13]:
df.isnull().sum()

student_id        0
name              0
age               3
gender            0
grade             0
math_score       17
english_score     8
science_score     0
enrolled_date     0
remarks           0
dtype: int64

In [14]:
df.loc[:, "name"] = df["name"].str.lower().str.title()

In [15]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [16]:
df["age"].unique()

array([16., nan, 17., 18.])

In [17]:
age_mean = df["age"].mean().round(0)

In [18]:
age_mean

np.float64(17.0)

In [19]:
df.loc[:, "age"] = df["age"].fillna(age_mean)

In [20]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [24]:
df["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [22]:
df.loc[:, "gender"] = df["gender"].str.lower().str.title()

In [23]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,Female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,Female,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,Male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,Female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,Female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,Male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,Female,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,Female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,Male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,Male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,Male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,Male,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,Female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,Male,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,Male,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,Female,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,Female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,Male,11,NaN,64,83,2022/06/11,Average

In [25]:
df["grade"]

0       11
1     10th
2       10
3       10
4       11
5       10
6       11
7       12
8       12
9       12
10    11th
11    11th
12      11
13      10
14      12
15      12
16      11
17    11th
18      10
19    11th
20      10
21      11
22    11th
23    11th
24    11th
25      12
26    10th
27      12
28      11
29      11
Name: grade, dtype: object

In [26]:
df["grade"].unique()

array(['11', '10th', '10', '12', '11th'], dtype=object)

In [27]:
df.loc[:, "grade"] = df["grade"].replace({'10th':'10', '11th':'11'})

In [28]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,Female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,Female,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,Male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,Female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,Female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,Male,11,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,Female,11,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,Female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,Male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,Male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,Male,11,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,Male,11,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,Female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,Male,11,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,Male,11,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,Female,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,Female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,Male,11,NaN,64,83,2022/06/11,Average

In [29]:
math_mean = df["math_score"].mean()

In [30]:
df.loc[:, "math_score"] = df["math_score"].fillna(math_mean)

In [31]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,Female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,Male,10,74.0,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,Female,10,74.0,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,Male,11,74.0,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,74.0,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,Female,12,74.0,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,Female,12,74.0,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,Male,11,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,Female,11,74.0,missing,95,2022-06-10,average
12,112,Patel R.,17.0,Female,11,74.0,87,89,2022-06-10,poor
13,113,Patel R.,17.0,Male,10,74.0,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,Male,12,74.0,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,74.0,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,Male,11,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,Male,11,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,74.0,missing,89,2022-06-10,average
21,121,John Doe,18.0,Female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,Male,11,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11,74.0,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,Male,11,74.0,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,Female,12,74.0,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,Female,11,74.0,64,89,2022-06-10,average
29,129,Patel R.,17.0,Male,11,74.0,64,83,2022/06/11,Average

In [ ]:
df["english_score"]

In [ ]:
df.loc[:, "english_score"] = pd.to_numeric(df["english_score"], errors='coerce')

In [ ]:
df

In [ ]:
df["enrolled_date"].unique()

In [ ]:
## yyyy-mm-dd

In [ ]:
dict_date={
    '10-06-2022':'2022-06-10',
    '06/12/2022':'2022-06-12', 
    '2022/06/11':'2022-06-11'
}

In [ ]:
df.loc[:, "enrolled_date"] = df["enrolled_date"].replace(dict_date)

In [ ]:
df

In [ ]:
df["enrolled_date"] = pd.to_datetime(df["enrolled_date"])

In [ ]:
df

In [ ]:
df["enrolled_date"]

In [ ]:
df["remarks"].unique()

In [ ]:
dict_remark = {
    'excellent': 'Excellent', 
    'GOOD': 'Good', 
    'needs improvement': 'Needs Improvement', 
    'average': 'Average', 
    'poor': 'Poor', 
    'good student': 'Good'
}

In [ ]:
df["remarks"].replace(dict_remark).unique()

In [ ]:
df.loc[:,"remarks"] = df["remarks"].replace(dict_remark)

In [ ]:
df

In [ ]:
# 1. Calculate Total Score
df['total_score'] = df['math_score'] + df['english_score']

In [ ]:
# 2. Gender-Based Performance Analysis
gender_performance = df.groupby('gender')[['math_score', 'english_score']].mean()
gender_performance

In [ ]:
# 3. Filter Students by Age (e.g., older than 15)
older_students = df[df['age'] > 15]
older_students

In [ ]:
# 4. Remarks Distribution Summary
remarks_summary = df['remarks'].value_counts()
remarks_summary

In [ ]:
# 5. Export Cleaned Data to CSV
df.to_csv('cleaned_student_data.csv', index=False)